CREATE SCHEMA POLLING_DEMO;

CREATE COLUMN TABLE POLLING_DEMO.ORDERS (
    ID NVARCHAR(36) PRIMARY KEY,
    CustomerID NVARCHAR(36),
    Amount DECIMAL(15,2),
    Currency NVARCHAR(3),
    Status NVARCHAR(50),
    CreatedAt TIMESTAMP,
    TotalWithTax DECIMAL(15,2),
    Priority NVARCHAR(20)
);